# Generated by Django 4.0.6 on 2022-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fires_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('bright_ti4', models.FloatField(verbose_name='Bright')),
                ('scan', models.FloatField(verbose_name='Scan')),
                ('track', models.FloatField(verbose_name='Bright')),
                ('acq_date', models.DateField(verbose_name='Data da Queimada')),
                ('acq_time', models.TimeField(verbose_name='Hora da Aquisição')),
                ('satellite', models.CharField(max_length=255, verbose_name='Satelite')),
                ('instrument', models.CharField(max_length=255, verbose_name='Tipo do Dataset')),
                ('confidence', models.CharField(max_length=255, verbose_name='Confiabilidade')),
                ('version', models.IntegerField(verbose_name='Versão')),
                ('bright_ti5', models.FloatField(verbose_name='Bright')),
                ('frp', models.FloatField(verbose_name='FRP')),
                ('daynight', models.IntegerField(verbose_name='Dia ou Noite')),
                ('type', models.IntegerField(verbose_name='Tipo do Local')),
            ],
        ),
    ]
