# Generated by Django 4.0.6 on 2022-08-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datafire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafire',
            name='acq_time',
            field=models.CharField(max_length=255, verbose_name='Hora que foi tirado'),
        ),
    ]
