version: '3.1'

services:
  db:
    container_name: tcc_database
    build: './DB/'
    ports:
      - "5432:5432"
  api:
    container_name: tcc_backend
    build: './TCC/'
    ports:
      - "8000:8000"